import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.css";

const _ = require("lodash");

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Timetable app</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="center flex h-screen justify-center bg-slate-200">
          <table className="m-8 table-auto border-spacing-4 rounded-md border-2 border-solid border-gray-400 p-8 text-center">
            <thead>
              <tr className="col-timings">
                <th style={{ writingMode: "unset" }}>Day of the week</th>
                <th>8:00</th>
                <th>8:10</th>
                <th>8:20</th>
                <th>8:30</th>
                <th>8:40</th>
                <th>8:50</th>
                <th>9:00</th>
                <th>9:10</th>
                <th>9:20</th>
                <th>9:30</th>
                <th>9:40</th>
                <th>9:50</th>
                <th>10:00</th>
                <th>10:10</th>
                <th>10:20</th>
                <th>10:30</th>
                <th>10:40</th>
                <th>10:50</th>
                <th>11:00</th>
                <th>11:10</th>
                <th>11:20</th>
                <th>11:30</th>
                <th>11:40</th>
                <th>11:50</th>
                <th>12:00</th>
                <th>12:10</th>
                <th>12:20</th>
                <th>12:30</th>
                <th>12:40</th>
                <th>12:50</th>
                <th>1:00</th>
                <th>1:10</th>
                <th>1:20</th>
                <th>1:30</th>
                <th>1:40</th>
                <th>1:50</th>
                <th>2:00</th>
                <th>2:10</th>
                <th>2:20</th>
                <th>2:30</th>
                <th>2:40</th>
                <th>2:50</th>
                <th>3:00</th>
                <th>3:10</th>
                <th>3:20</th>
                <th>3:30</th>
                <th>3:40</th>
                <th>3:50</th>
                <th>4:00</th>
                <th>4:10</th>
                <th>4:20</th>
                <th>4:30</th>
                <th>4:40</th>
                <th>4:50</th>
                <th>5:00</th>
                <th>5:10</th>
                <th>5:20</th>
                <th>5:30</th>
                <th>5:40</th>
                <th>5:50</th>
                <th>6:00</th>
                <th>6:10</th>
                <th>6:20</th>
                <th>6:30</th>
                <th>6:40</th>
                <th>6:50</th>
                <th>7:00</th>
                <th>7:10</th>
                <th>7:20</th>
                <th>7:30</th>
                <th>7:40</th>
                <th>7:50</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td>Monday</td>
                {_.times(72, () => (
                  <td className="zero">0</td>
                ))}
              </tr>
              <tr>
                <td>Tuesday</td>
                {_.times(72, () => (
                  <td className="one">1</td>
                ))}
              </tr>
              <tr>
                <td>Wednesday</td>
              </tr>
              <tr>
                <td>Thursday</td>
              </tr>
              <tr>
                <td>Friday</td>
              </tr>
              <tr>
                <td>Saturday</td>
              </tr>
              <tr>
                <td>Sunday</td>
              </tr>
            </tbody>
          </table>
        </div>
      </main>
    </>
  );
}
